# Generated by Django 4.0.4 on 2022-08-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
