# Generated by Django 4.0.4 on 2022-08-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studio_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='photo_category',
        ),
    ]
