# Generated by Django 4.0.4 on 2022-08-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_studio_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='pic_folder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='post_num',
            field=models.CharField(default='', max_length=5),
        ),
    ]
