# Generated by Django 4.0.4 on 2022-08-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_studio_pic_folder_alter_studio_post_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='ceo_id',
            new_name='ceo',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='contact',
        ),
    ]
