# Generated by Django 4.0.4 on 2022-08-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact'),
        ('studio', '0004_rename_ceo_id_studio_ceo_remove_studio_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('studio', models.ForeignKey(db_column='studio_id', on_delete=django.db.models.deletion.CASCADE, related_name='studio_id', to='studio.studio')),
                ('user', models.ManyToManyField(db_column='user_question', related_name='user_question', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='studio.question')),
                ('user', models.ManyToManyField(db_column='user_answer', related_name='user_answer', to='accounts.user')),
            ],
        ),
    ]
