# Generated by Django 4.0.4 on 2022-08-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
