# Generated by Django 4.0.4 on 2022-08-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_remove_question_studio_remove_question_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='ceo',
            new_name='ceo_id',
        ),
    ]
