# Generated by Django 4.0.4 on 2022-08-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_rename_ceo_studio_ceo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='pic_folder',
        ),
        migrations.AddField(
            model_name='studio',
            name='info',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='insta_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='intro',
            field=models.TextField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='studio_photo')),
                ('title', models.CharField(max_length=20)),
                ('camera', models.CharField(max_length=20)),
                ('studio_portfolio', models.ForeignKey(db_column='studio_id_photo', on_delete=django.db.models.deletion.CASCADE, related_name='studio_portfolio', to='studio.studio')),
            ],
        ),
    ]
