# Generated by Django 4.0.4 on 2022-08-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_remove_studio_pic_folder_studio_info_studio_insta_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
