# Generated by Django 4.0.4 on 2022-08-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact'),
        ('question', '0003_alter_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='studio',
            new_name='studio_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='user_question_id',
            field=models.ForeignKey(db_column='user_question_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_id', to='accounts.user'),
            preserve_default=False,
        ),
    ]
