# Generated by Django 4.0.4 on 2022-08-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact'),
        ('answer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(db_column='user_answer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='accounts.user'),
        ),
    ]
