# Generated by Django 4.0.4 on 2022-08-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact'),
        ('answer', '0004_alter_answer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_answer_id',
            field=models.ForeignKey(db_column='user_answer_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_id', to='accounts.user'),
            preserve_default=False,
        ),
    ]
