# Generated by Django 4.0.4 on 2022-08-19 10:20

from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=photo.models.get_img_storage_path)),
                ('title', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('studio_portfolio', models.ForeignKey(db_column='studio_id_photo', on_delete=django.db.models.deletion.CASCADE, related_name='studio_portfolio', to='studio.studio')),
            ],
        ),
    ]
